# Generated by Django 5.0 on 2024-01-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_follower',
            new_name='user_followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_following',
        ),
    ]
